sonar.projectKey=leozztto_lmffinpro_frontend
sonar.organization=leozztto
sonar.projectName=LmfFinPro Frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/vite-env.d.ts
sonar.coverage.exclusions=src/main.tsx,src/vite-env.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
